## Basic Configuration

baseurl = "http://127.0.0.1:4800"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Douglas Vinícius"
title = "Projeto Regressão"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Análise de Regressão" 
intro = "Projeto de Análise de Regressão"
description = "Tópicos sobre Regressão Linear, Múltipla, Diagnóstico, ..."
authorimage = "icon_linear_regression.svg"
dateformat = "Jun 24, 2019"

## Site Meta Settings
[params.meta]
description = "Website sobre Análise de Regressão e RMarkdown"
keywords = "minimalist,blog,goa,hugo,developer,linear,regression,rmarkdown,"


## Social Accounts
[params.social]
github = "Doug7Vinicius"
instagram = "Jossivanaaa"
linkedin = "douglasvinicius7"
stackoverflow = "11490202/douglas-vinícius"

## Extras
[params.extra]
copyright = "© 2019. Douglas Vinícius. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "sobre"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "projeto"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"
